### ISSUE TITLE
Setup a build task

### ISSUE THREAD

**Issue by kdinev** [Infragistics/zero-blocks#6]
There should be npm scripts that produce combined files.
There should be a build setup to run with every commit.

**Comment by damyanpetev** [comment]
@kdinev can a take a look at https://github.com/damyanpetev/zero-blocks/commit/84eee8b74e29681564d1eb87f86908f25ffe2a94 when you get the chance. 

**Notes:**
- Templates are inlined for the bundle - if we want to keep them as separate requests for the per-module js files there should be yet another task to build those with and without tempaltes and copy them too.
- Did my best to ignore most of the files the bundle produces to reduce constant merge conflicts, but did test a `npm install` from the _dist_ folder locally and everything seems to run rather smoothly with the bundled file and css on client side and `import * as Infragistics from 'zero-blocks/main'` though the typings. Add a readme and some task tweaks and those are good to go for npm.
- From above the demos page for #4 should be able to run mostly on CDN resource like https://github.com/IgniteUI/igniteui-angular2 with just the min.js and css.
-  Lastly - had to use temporary 'zero-blocks' folder for output to produce the correct bundle module names, which turned out a bit messy and no config worked around that. Perhaps we can rename either the _dist_ or _src_ folders instead to avoid having to delete it and move files around?

Still have't tested using source filed directly without the bundle, but let me know what you think and if I should PR that branch in.

**Comment by kdinev** [comment]
@damyanpetev Do you suggest to rename `dist` to `zero-blocks`? The rest seems good to me.

**Comment by damyanpetev** [comment]
@kdinev Or the source the same way Angular had modules/angular and is now [modules/@angular](https://github.com/angular/angular/tree/master/modules/%40angular) folder - the bundled module names are created based on relative paths so they match file imports without need to change code.

The extra folder (while extra hassle) still works and I realize the repetition would look super awkward in our current setup so how about we try as is for now.

**Comment by kdinev** [comment]
Alright! Setup the pull request :)
